# Pandas study notes

This notebook collects a few beginner-friendly pandas examples for working with site data.

## 1. Create a DataFrame

The next cell creates a DataFrame from a dictionary of site information.

In [5]:
%pip install pandas
import pandas as pd

Requirement already satisfied: pandas in c:\Users\jemim\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\jemim\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\jemim\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\jemim\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\jemim\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:

site_data = {
    'site_id': [1, 2, 3, 4, 5, 6],
    'site_name': ['Chennai Central', 'Mumbai North', 'Delhi South', 'Bangalore East', 'Hyderabad West', 'Pune Metro'],
    'country': ['India', 'India', 'India', 'India', 'India', 'India'],
    'status': ['Active', 'Active', 'Pending', 'Active', 'Closed', 'Pending'],
    'enrolled_count': [22, 15, 8, 30, 12, 5],
    'days_to_activation': [45, 60, None, 38, 55, None],
}

df = pd.DataFrame(site_data)

df.head() ##shows the first few rows of a DataFrame.

,site_id,site_name,country,status,enrolled_count,days_to_activation
0,1,Chennai Central,India,Active,22,45.0
1,2,Mumbai North,India,Active,15,60.0
2,3,Delhi South,India,Pending,8,NaN
3,4,Bangalore East,India,Active,30,38.0
4,5,Hyderabad West,India,Closed,12,55.0

## 2. Inspect the DataFrame

Use these commands to understand the structure of the data.

In [7]:
print(df.shape) ##shows the number of rows and columns in the DataFrame
print(df.columns) ##shows the column names
df.info() ##shows information about the DataFrame

(6, 6)
Index(['site_id', 'site_name', 'country', 'status', 'enrolled_count',
       'days_to_activation'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   site_id             6 non-null      int64
 1   site_name           6 non-null      str
 2   country             6 non-null      str
 3   status              6 non-null      str
 4   enrolled_count      6 non-null      int64
 5   days_to_activation  4 non-null      float64
dtypes: float64(1), int64(2), str(3)
memory usage: 420.0 bytes

## 3. Filter rows

These examples show how to select rows based on conditions.

In [8]:
# Pending sites and their activation days
pending_sites = df[df['status'] == 'Pending'][['site_name', 'days_to_activation']] ##filters the DataFrame to include only rows where the 'status' column is 'Pending' and selects only the 'site_name' and 'days_to_activation' columns.   
pending_sites.sort_values('days_to_activation', ascending=True) ##sorts the filtered DataFrame by the 'days_to_activation' column in ascending order.

     site_name  days_to_activation
2  Delhi South                 NaN
5   Pune Metro                 NaN

## 4. Select columns

This shows how to keep only the columns you need.

In [9]:
df[['site_name', 'enrolled_count']]

         site_name  enrolled_count
0  Chennai Central              22
1     Mumbai North              15
2      Delhi South               8
3   Bangalore East              30
4   Hyderabad West              12
5       Pune Metro               5

## 5. Sort and view top results

This helps you rank sites by a column.

In [10]:
top_sites = df.sort_values('enrolled_count', ascending=False).head(3)
top_sites

,site_id,site_name,country,status,enrolled_count,days_to_activation
3,4,Bangalore East,India,Active,30,38.0
0,1,Chennai Central,India,Active,22,45.0
1,2,Mumbai North,India,Active,15,60.0

## 6. Export a filtered result

This example saves a filtered DataFrame to a CSV file.

In [ ]:
high_performers = df[(df['enrolled_count'] > 15) & (df['status'] == 'Active')][['site_name', 'enrolled_count']]
high_performers.to_csv('high_performers.csv', index=False) ##saves the filtered DataFrame to a CSV file named 'high_performers.csv' without including the index column.
high_performers

         site_name  enrolled_count
0  Chennai Central              22
3   Bangalore East              30

Write a single block of code that:

Filters for sites that are not Closed
Shows only site_name, status, and enrolled_count
Sorts by enrolled_count descending
Shows top 4 results
Saves the output to a CSV called site_review.csv

In [21]:
Open_sites = df[df["status"] != "Closed"][["site_name", "status", "enrolled_count"]].sort_values("enrolled_count", ascending=False).head(4)
Open_sites.to_csv('site_review.csv', index=False)
print(Open_sites)

         site_name   status  enrolled_count
3   Bangalore East   Active              30
0  Chennai Central   Active              22
1     Mumbai North   Active              15
2      Delhi South  Pending               8