In [15]:
%pip install pandas
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in c:\Users\jemim\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\jemim\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\jemim\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\jemim\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\jemim\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
tasks = {
    "task_id": [101, 102, 103, 104, 105, 106],
    "task_name": [
        "Site Activation",
        "Regulatory Submission",
        "Patient Recruitment",
        "Database Lock",
        "Monitoring Visit",
        "Final Study Report"
    ],
    "site_name": [
        "Chennai Site",
        "Mumbai Site",
        "Bangalore Site",
        "Hyderabad Site",
        "Delhi Site",
        "Pune Site"
    ],
    "owner": [
        "Sharon",
        "Amit",
        "Priya",
        "Rahul",
        "Neha",
        "Kiran"
    ],
    "days_overdue": [
        15,   # Overdue
        4,    # Overdue
        0,    # Due today (on time)
        -3,   # Not yet due
        -10,  # Not yet due
        1     # Slightly overdue
    ]
}

In [8]:
df = pd.DataFrame(tasks)
df.head()

   task_id              task_name       site_name   owner  days_overdue
0      101        Site Activation    Chennai Site  Sharon            15
1      102  Regulatory Submission     Mumbai Site    Amit             4
2      103    Patient Recruitment  Bangalore Site   Priya             0
3      104          Database Lock  Hyderabad Site   Rahul            -3
4      105       Monitoring Visit      Delhi Site    Neha           -10

In [9]:
def rag_status(row):
    if row['days_overdue'] > 7:
        return 'Red'
    elif row['days_overdue'] > 0:
        return 'Amber'
    else:
        return 'Green'
    
df['rag'] = df.apply(rag_status, axis=1)
df.head()

   task_id              task_name       site_name   owner  days_overdue    rag
0      101        Site Activation    Chennai Site  Sharon            15    Red
1      102  Regulatory Submission     Mumbai Site    Amit             4  Amber
2      103    Patient Recruitment  Bangalore Site   Priya             0  Green
3      104          Database Lock  Hyderabad Site   Rahul            -3  Green
4      105       Monitoring Visit      Delhi Site    Neha           -10  Green

In [13]:
summary = df.groupby('rag')['task_name'].count().reset_index()
summary.columns = ['Status', 'Task Count']
summary.head()

  Status  Task Count
0  Amber           2
1  Green           3
2    Red           1

In [14]:
df.to_csv('flagged_tasks_output.csv', index=False)
summary.to_csv('rag_summary.csv', index=False)

print("Done. Files exported.")
print(summary)

Done. Files exported.
  Status  Task Count
0  Amber           2
1  Green           3
2    Red           1